#!/bin/bash
set -euo pipefail

cat << "EOF"

__      __          _             
\ \    / /___  ___ | |__ ___  _ _ 
 \ \/\/ // -_)/ -_)| / // -_)| '_|
  \_/\_/ \___|\___||_\_\\___||_|  

EOF

.devcontainer/run/test

pnpm --frozen-lockfile install
