name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/weekerhq/weeker/devcontainer
          cacheFrom: ghcr.io/weekerhq/weeker/devcontainer
          push: never
          runCmd: run/ci
